### ISSUE TITLE
Polygon Conversion issue for YOLOv8 Semantic Segmentation

### ISSUE THREAD

**Issue by Arshadoid** [GreatV/labelme2yolo#14]
When Converting below provided annotation file I get some points which are bigger than 1. What can be a reason for this?
```
{
	"version": "3.16.7",
	"flags": {},
	"shapes": [
		{
			"label": "cable",
			"line_color": null,
			"fill_color": null,
			"points": [
				[
					0.0,
					1185.46875
				],
				[
					12.261904761904772,
					1152.5223214285716
				],
				[
					964.6428571428571,
					831.09375
				],
				[
					2260.2140077821015,
					394.789640077821
				],
				[
					2870.136186770428,
					187.13521400778215
				],
				[
					3420.0,
					0.0
				],
				[
					3436.2840466926074,
					3.2830739299610895
				],
				[
					2952.7380952380956,
					174.84375
				],
				[
					2232.5,
					425.9598214285714
				],
				[
					1340.9533073929964,
					728.842412451362
				],
				[
					501.9455252918288,
					1016.1113813229573
				]
			],
			"shape_type": "polygon",
			"flags": {}
		}
	],
	"lineColor": [
		0,
		255,
		0,
		128
	],
	"fillColor": [
		255,
		0,
		0,
		128
	],
	"imagePath": "14_00354.jpg",
	"imageData": REMOVED,
	"imageHeight": 2160,
	"imageWidth": 3840
} 
```

OUTPUT:

0 0.0 **1.157684326171875** 0.011974516369047629 **1.1255100795200894** 0.9420340401785714 0.811614990234375 **2.2072402419747084** 0.38553675788849706 **2.8028673698929962** 0.18274923242947474 **3.33984375** 0.0 **3.3557461393482493** 0.0032061268847276263 **2.8835332961309526** 0.170745849609375 **2.18017578125** 0.41597638811383925 **1.309524714250973** 0.7117601684095332 0.49018117704280156 0.9922962708232005

I'm using:
- labelme2yolo Version: 0.0.9
- Python 3.11.0
- Windows 11

Also, 99 annotation files out of 922 have this issue, and rest seem fine. I double checked all the files with this issue and all of the points are within the image size range. I attached the file as .txt (github doesn't accept .json) so the issue can be reproduced if needed. 
[14_00354.txt](https://github.com/GreatV/labelme2yolo/files/11085715/14_00354.txt)

**Comment by GreatV** [comment]
Thank you for your feedback, I will check out the problem as soon as possible.

**Comment by GreatV** [comment]
Hi, @Arshadoid. The `imageWidth` and `imageHieght` your json file are not the same as the `imageData` size. (2160x3840 vs. 1024x1204).

**Comment by Arshadoid** [comment]
> Hi, @Arshadoid. The `imageWidth` and `imageHieght` your json file are not the same as the `imageData` size. (2160x3840 vs. 1024x1204). You need to use the label of the cropped image.

Hi @GreatV Thanks for looking into this and pointing out the issue. Seems like labelme2yolo expects to have *.png images in the same folder otherwise it generates it from imagedata. In my case easy solution would be just to modify  save_yolo_image function to point to original jpg images, as I have correct dimensions in jpg format, so it can get h and w. Thank you!
