### ISSUE TITLE
Train, Validation and Test split overlap

### ISSUE THREAD

**Issue by Arshadoid** [GreatV/labelme2yolo#15]
I was reviewing the files which were split by labelme2yolo and noticed that the function create splits with overlap.

In my case I have 1231 files, and I pass val_size=0.15 and test_size=0.1 and as the result of this it was split:

train=922
validation=185
test=124

Issues:

The amount of files by split seems fine. 
1. But when I move all split files (images or annotations) into a single folder file manager says the file exists and I skipped the same files. This resulted in total of 1077 files. This means 154 files were not utilized.
2. Verified duplicates with a python script:
- Overlap between Train and Val: 141 files
- Overlap between Train and Test: 0 files
- Overlap between Val and Test: 13 files 

Currently I'm trying to find out why it's not right, but could you please also check this. 

Also this issue was reported in the original branch. https://github.com/rooneysh/Labelme2YOLO/issues/5

**Comment by Arshadoid** [comment]
this part of the code is not correct I believe:
```
train_idxs, test_idxs = train_test_split(
    range(tmp_train_len), test_size=test_size / (1 - val_size))
```
I think it should be:
```
train_idxs, test_idxs = train_test_split(
    train_idxs, test_size=test_size / (1 - val_size))
```
as we want to split already created train indexes further for new train and test. Will test and post the result here.

**Comment by Arshadoid** [comment]
@GreatV I just tested and seems like it works correctly now. I commited the updated code to the repo. 

1. Verified duplicates with a python script:
- Overlap between Train and Val: 0 files
- Overlap between Train and Test: 0 files
- Overlap between Val and Test: 0 files

2. Amount of combined split files are now matching the total amount.

**Comment by GreatV** [comment]
@Arshadoid Thanks for the feedback, you can submit a pr to fix the issue.

**Comment by Arshadoid** [comment]
> @Arshadoid Thanks for the feedback, you can submit a pr to fix the issue.

Thank, will do now. This will be my first contribution :)

**Comment by Arshadoid** [comment]
Issues was fixed.
