### ISSUE TITLE
I tested in the example folder of labelme, and the resulting folders were all empty.

### ISSUE THREAD

**Issue by ZJDATY** [GreatV/labelme2yolo#19]
I tested in the example folder of labelme, and the resulting folders were all empty.

`labelme\examples\instance_ segmentation\data_ annotated`
![image](https://user-images.githubusercontent.com/29767049/235490915-04d078c4-3af0-468b-80b3-23da0642de2f.png)
![image](https://user-images.githubusercontent.com/29767049/235490962-442abf3f-2193-4fba-806c-6e3a98737756.png)
![image](https://user-images.githubusercontent.com/29767049/235491072-6575c666-5ced-4244-973f-cce70ddf0926.png)
![image](https://user-images.githubusercontent.com/29767049/235491250-0b3f9304-c372-40b2-9a71-78134c337028.png)
The folder in images and the folder in labels are both empty.

**Comment by GreatV** [comment]
hi @ZJDATY, maybe you need to set the value of val_size.
