### ISSUE TITLE
Error on convert only one file

### ISSUE THREAD

**Issue by terasadi** [GreatV/labelme2yolo#24]
When you have only one file to convert on folder the app crash.
It's a easy bug to reproduce.

**Comment by GreatV** [comment]
Hi @terasadi, Thank you for your feedback. This is generated by `sklearn.model_selection.train_test_split`. 

```
ValueError: With n_samples=1, test_size=0.25 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
```

We will implement `train_test_split` manually.
