### ISSUE TITLE
Doubt about the result format

### ISSUE THREAD

**Issue by terasadi** [GreatV/labelme2yolo#25]
YOLOv[X] use the following format:

![image](https://github.com/GreatV/labelme2yolo/assets/75371377/3cd0bdf6-4514-436d-9209-84c1fec7687f)
![image](https://github.com/GreatV/labelme2yolo/assets/75371377/3851461b-e30a-442a-b595-553445b312e8)

Since:
- One row per object
- The columns are **class**, **x_center**, **y_center**, **width**, and **height** format.
- These box coordinates must be normalized to the dimensions of the image (i.e. have values between 0 and 1)
- Class numbers are zero-indexed (start from 0).

Are five columns at all.
Why labelme2yolo result on nine columns?

Ex.:
6 0.30028237951807224 0.6704261490406068 0.4816327811244979 0.6704261490406068 0.4816327811244979 0.8132195448460507 0.30028237951807224 0.8132195448460507
0 -0.000571034136546178 0.47830209727800094 0.12583458835341366 0.47830209727800094 0.12583458835341366 0.7038933511825078 -0.000571034136546178 0.7038933511825078

**Comment by terasadi** [comment]
I found my error... bbox for output_format.
Thank you.

**Comment by GreatV** [comment]
Hi @terasadi, For the `--output_format bbox`, the current release version is buggy and you may need to build the cli tool manually from the latest source code.
