### ISSUE TITLE
Cannot convert to yolov8n segmentation  format

### ISSUE THREAD

**Issue by dauntless23** [GreatV/labelme2yolo#34]
I prepared my dataset in Labelme and whenever i try to convert to yolo format,  the operation completes successfully but i somehow seem to always get the bounding boxes, and not the segments. i even specified output_format argument to "plygon",  but still got bboxs

**Comment by GreatV** [comment]
Hi @dauntless23, can you provide a sample file, and the convert command you used, so I can make an attempt to figure out the problem?

**Comment by dauntless23** [comment]
At first I was using an old Labelme2YOLO install so it didnt work.
When i updated it, it just didnt output anything to the training and test directories.
I figured out where I was going wrong. I had made a mistake, and not included the image data on my custom data whilst using labelme. its now all sorted
