### ISSUE TITLE
Issue converting labelme JSON to YOLODataset

### ISSUE THREAD

**Issue by zaheerkzz** [GreatV/labelme2yolo#35]
Here is my _labelme_ **JSON**:

`{
    "version": "5.3.1",
    "flags": {},
    "shapes": [
        {
            "label": "Center",
            "points": [
                [
                    1400,
                    900
                ],
                [
                    1500,
                    900
                ],
                [
                    1500,
                    1000
                ],
                [
                    1400,
                    1000
                ]
            ],
            "group_id": null,
            "description": "",
            "shape_type": "Rectangle",
            "flags": {}
        },
        {
            "label": "LeftGaurd",
            "points": [
                [
                    1320,
                    920
                ],
                [
                    1420,
                    920
                ],
                [
                    1420,
                    1020
                ],
                [
                    1320,
                    1020
                ]
            ],
            "group_id": null,
            "description": "",
            "shape_type": "Circle",
            "flags": {}
        },
        {
            "label": "LeftTackle",
            "points": [
                [
                    1240,
                    920
                ],
                [
                    1340,
                    920
                ],
                [
                    1340,
                    1020
                ],
                [
                    1240,
                    1020
                ]
            ],
            "group_id": null,
            "description": "",
            "shape_type": "Circle",
            "flags": {}
        }
    ],
    "imagePath": "img/latest-00-QBShotGun-WRLeftHashmarkOn-WRRightHashmarkOn-FeatherLeft-WRRightHashmarkOff-FeatherRight-normal-16686378232057195.png",
    "imageData": "",
    "imageHeight": 1200,
    "imageWidth": 2500
}`

Im trying to convert to **YOLO** Dataset using this command:
`labelme2yolo --json_dir json --val_size 0.15 --test_size 0.15`

It Generates a Folders **YOLODataset** -> **images, label** -> **test, train val**, but the folders are empty.

Im using:

```
Python 3.10.12
YoloV5
labelme2yolo 0.1.2 
```
please help with this issue.
Thanks

**Comment by GreatV** [comment]
Hi @zaheerkzz, `imageData` is None. You have to make sure the `imageData` has content.

**Comment by zaheerkzz** [comment]
the image data is correct, i run with this https://github.com/rooneysh/Labelme2YOLO script and the issue fixed.
