### ISSUE TITLE
labelme2yolo some error

### ISSUE THREAD

**Issue by Galaxy-Ding** [GreatV/labelme2yolo#48]
Here is my json
`
{
  "version": "0.3.3",
  "flags": {},
  "shapes": [],
  "imagePath": "KunChuansafebelt_dinglinhe20240119a_000119.jpg",
  "imageData": null,
  "imageHeight": 1080,
  "imageWidth": 1920
}
`
Im trying to convert to YOLO Dataset using this command:
`labelme2yolo --json_dir json --val_size 0.15 --test_size 0.15`

Im using:
![image](https://github.com/GreatV/labelme2yolo/assets/54030287/f8751d85-1a60-450d-8609-4763cbeeb6dd)

![image](https://github.com/GreatV/labelme2yolo/assets/54030287/07e18cf9-e302-479f-bdd5-afb960d93328)

what errors
![image](https://github.com/GreatV/labelme2yolo/assets/54030287/992abddb-eac8-442a-92f4-e255bea43214)

I know the reason is that the imageData of json is empty, so the image cannot be saved. I know how to change it, but would like the author to update it too

**Comment by GreatV** [comment]
Hi @Galaxy-Ding, thanks for the feedback, feel free to submit a PR to fix it.
