### ISSUE TITLE
the pip package output a different file name

### ISSUE THREAD

**Issue by MoAbbasid** [GreatV/labelme2yolo#53]
The labelme2yolo pip package has different outputs from @rooneysh's labelme2yolo python program,
the output text file name are differenet (randomly generated) while the original output the text having the same file name it was created from.
also when running it with output_format set to polygon, the values are different than the original's output when using --seg flag, which im inclined to believe is the correct one.

**Comment by GreatV** [comment]
hi @MoAbbasid, this project has significantly diverged from the original, so if you're familiar with the original, you might prefer to continue using it.

**Comment by MoAbbasid** [comment]
@GreatV , thank you for your response
some Question, does yolo training work with your naming convention?
 how are the coordinates calculated in your project?
also yours has a neat way of specifying test_size and val_size, while the original only has val_size arg and no option to set it to zero, any idea of how to set val_size to 0 in the original?

**Comment by MoAbbasid** [comment]
@GreatV so in YOLO the label names do not have to be the same as the image names for it to be able to train, am I correct?
