### ISSUE TITLE
file name changed

### ISSUE THREAD

**Issue by YingGit-Zhao** [GreatV/labelme2yolo#55]
When I use labelme2yolo to convert my label format, I find that the converted file name becomes a set of hexadecimal numbers, how do I change this problem

**Comment by GreatV** [comment]
just change this line

https://github.com/GreatV/labelme2yolo/blob/04f7d2d259011fd179a692fb7d03dc801d3a59d8/src/labelme2yolo/l2y.py#L263

**Comment by YingGit-Zhao** [comment]
> just change this line
> 
> https://github.com/GreatV/labelme2yolo/blob/04f7d2d259011fd179a692fb7d03dc801d3a59d8/src/labelme2yolo/l2y.py#L263

Ok, I have solved the problem, thank you
