### ISSUE TITLE
Multiprocessing error on high core count maschines

### ISSUE THREAD

**Issue by janb14** [GreatV/labelme2yolo#58]
Due to the nature of pythons own multiprocessing module and its pool implementation, machines that report more than 64 logical cores with os.cpu_count() will crash the pool creation.
Our server has 128 cores which results in the following error:
ValueError: need at most 63 handles, got a sequence of length 129

A possible solution would be to change line 250 in l2y.py from:
with Pool(os.cpu_count()-1) as pool...
to
with Pool(min(os.cpu_count()-1, 63)) as pool....

Best Regards.

**Comment by GreatV** [comment]
Hi @janb14, would you be interested in submitting a PR to fix this issue?
