### ISSUE TITLE
Only one sample in train and val

### ISSUE THREAD

**Issue by sailor239** [GreatV/labelme2yolo#68]
Hi, I have totally 16 labelled images (png + json). But after running the command, there is only one in train and one in val. May I know what has gone wrong? Thank you!
<img width="172" alt="image" src="https://github.com/user-attachments/assets/7ad5fc02-b64d-48cd-9ec9-dc9460d677aa">

**Comment by GreatV** [comment]
Which version are you using?

**Comment by sailor239** [comment]
0.2.4 Below is the command I used: labelme2yolo --json_dir /Users/xxx/Documents/project/train/

**Comment by GreatV** [comment]
Could you try it with 0.2.0? it might be caused by parallelization.

**Comment by GreatV** [comment]
Would you mind providing some logs, I can't reproduce the issue.

**Comment by sailor239** [comment]
Thanks for the fast response! Just tried. Now I have the 16 images organized into 12 for train and 4 for val. But for the labels, there is still only one txt file.

**Comment by GreatV** [comment]
Versions smaller than 0.2 are more stable, just a lot slower, so maybe you could try that.

**Comment by sailor239** [comment]
> Would you mind providing some logs, I can't reproduce the issue.

There is actually no error. My file names are like "a.b.png" and "a.b.json". Could this be the cause?

**Comment by sailor239** [comment]
> > Would you mind providing some logs, I can't reproduce the issue.
> 
> There is actually no error. My file names are like "a.b.png" and "a.b.json". Could this be the cause?

I think this is the issue. I renamed my files to "a.png" and "a.json". Now I get all the outputs correctly. Perhaps the parsing of file names needs to be updated. Thanks again!

**Comment by GreatV** [comment]
Thanks for the feedback, I'll try to fix the issue next.

**Comment by sailor239** [comment]
> Thanks for the feedback, I'll try to fix the issue next.

No problem. Great work mate!
