### ISSUE TITLE
Bug，There is a problem with the number of images under centos

### ISSUE THREAD

**Issue by wu-yang-work** [GreatV/labelme2yolo#70]
after run labelme2yolo --json_dir /home/hzadmin/python_project/go2/ningbo_chusui/data --val_size 0.15 --test_size 0.15
    (env_all) (base) [hzadmin@DsjAI ningbo_chusui]$ labelme2yolo --json_dir /home/xx/data --val_size 0.15 --test_size 0.15
[2024-09-06T08:15:58Z INFO  labelme2yolo] Starting the conversion process...
[2024-09-06T08:15:58Z INFO  labelme2yolo] Read and parsed 621 JSON files.
  [Train] [00:00:00] [########################################] 433/433 (0s)
  [Val] [00:00:00] [########################################] 94/94 (0s)
  [Test] [00:00:00] [########################################] 94/94 (0s)
[2024-09-06T08:15:59Z INFO  labelme2yolo] Creating dataset.yaml file...
[2024-09-06T08:15:59Z INFO  labelme2yolo] Conversion process completed successfully.

It runs successfully，But when I counted the number of images and txt files, I noticed something was wrong
`images_dir = '/home/xx/data/YOLODataset/images'
    labels_dir = '/home/xx/data/YOLODataset/labels'

    total_images_li = glob.glob(os.path.join(images_dir, '*', '*.jpg'), recursive=True)
    total_labels_li = glob.glob(os.path.join(labels_dir, '*', '*.txt'), recursive=True)
    print(len(glob.glob(os.path.join(images_dir, 'train', '*.jpg'))))
    print(len(glob.glob(os.path.join(images_dir, 'test', '*.jpg'))))

    print(len(glob.glob(os.path.join(images_dir, 'val', '*.jpg'))))

    print(len(total_images_li))
    print(len(total_labels_li))`
    
    this is it's output
336
72
70
478
621
There are 143 images missing，I ran it multiple times and changed test_size, the result was the same, however, under windows it worked。i install labelme2yolo use pip

**Comment by GreatV** [comment]
You might try using the latest version or a version lower than 0.2.

**Comment by GreatV** [comment]
@wu-yang-work How did you solve this issue?
