### ISSUE TITLE
Background images are removed

### ISSUE THREAD

**Issue by janbrueggenjuergen** [GreatV/labelme2yolo#71]
Yolo models such as yolov9 and its implementation by [WongKinYiu](https://github.com/WongKinYiu/yolov9) accept background images during training not containing any classes. This is usually solved by mixing images with blank labels or just the images into the dataset. 

The current implementation sorts out images with no corresponding label file. 

Maybe a switch to include images without labels and maybe one to generate empty label files would be a great enhancement.

Best regards

**Comment by GreatV** [comment]
fixed by 
- https://github.com/GreatV/labelme2yolo/pull/72
